# Generated by Django 4.0.8 on 2023-07-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_level_alter_course_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Titulo',
            new_name='Titulo',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='Titulo',
            new_name='Titulo',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='Titulo',
            new_name='Titulo',
        ),
    ]
