# Generated by Django 4.0.8 on 2023-07-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_newsandevents_id_alter_semester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='Tipo',
            field=models.CharField(choices=[('News', 'Noticia'), ('Event', 'Evento')], max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero')], max_length=10),
        ),
    ]
