# Generated by Django 4.0.8 on 2023-07-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_newsandevents_posted_as_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsandevents',
            old_name='Descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='newsandevents',
            old_name='Tipo',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='newsandevents',
            old_name='Titulo',
            new_name='Titulo',
        ),
    ]
